version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # - ./src/scripts/sql:/docker-entrypoint-initdb.d
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - ${M_PORT}:${DB_PORT}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    links:
      - postgresdb
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app
