version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./src/scripts/sql:/docker-entrypoint-initdb.d
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    links:
      - postgresdb
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./src:/app
