version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./src/scripts/sql:/docker-entrypoint-initdb.d
      - ./postgresql-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
